creation_rules:
  - path_regex: secrets/.*\.yaml$
    encrypted_regex: ^(data|stringData)$
    # Replace this with your age public key.
    # You can get it by running: age-keygen -y /path/to/your/nix-secret/age.key
    age: age1kqe6893gvd2gvu3qgjgyfhw6242lyvpqde3lyrkh667230nh2vssjemds4
